background {
    path = screenshot
    blur_passes = 4
    blur_size = 7
    brightness = 0.5
    contrast = 0.8
}

label {
    text = cmd[update:1000] date +"%H:%M"
    font_size = 64
    position = 0, 200
    halign = center
    valign = center
    color = rgb(255, 255, 255)
}

label {
    text = cmd[update:1000] date +"%A, %d %B"
    font_size = 20
    position = 0, 130
    halign = center
    valign = center
    color = rgb(200, 200, 200)
}

label {
    text = Hi, $USER
    font_size = 25
    position = 0, 50
    halign = center
    valign = center
    color = rgb(255, 255, 255)
}

input-field {
    size = 250, 50
    outline_thickness = 3
    outer_color = rgb(151515)
    inner_color = rgb(200, 200, 200)
    font_color = rgb(10, 10, 10)
    placeholder_text = Password...
    fail_text = Wrong password!
    position = 0, -30
    halign = center
    valign = center
    fade_on_empty = false
    dots_size = 0.25
    dots_spacing = 0.15
}
