globinclude kitty.d/**/*.conf

foreground #cad3f5
background #1f1e24
background_opacity 0.9
background_blur 64

shell_integration no-title
confirm_os_window_close 0

map shift+enter send_text all \e\r
