color_theme = "Default"
theme_background = False
truecolor = True
vim_keys = False
rounded_corners = True
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 2000
proc_sorting = "memory"
proc_colors = True
proc_gradient = True
proc_mem_bytes = True
proc_cpu_graphs = True
check_temp = True
show_uptime = True
show_cpu_freq = True
clock_format = "%X"
