# Catppuccin Macchiato Custom

foreground #cad3f5
background #1f1e24

cursor #f4dbd6
cursor_text_color #181926

selection_foreground #cad3f5
selection_background #3a3e53

# Black
color0 #494d64
color8 #5b6078

# Red
color1 #ed8796
color9 #ed8796

# Green
color2 #a6da95
color10 #a6da95

# Yellow
color3 #eed49f
color11 #eed49f

# Blue
color4 #8aadf4
color12 #8aadf4

# Magenta
color5 #f5bde6
color13 #f5bde6

# Cyan
color6 #8bd5ca
color14 #8bd5ca

# White
color7 #a5adcb
color15 #b8c0e0
